a.out:
	../struct2json student_define.h
	g++ -Iinclude -I. student.cpp main.cpp 
	echo "\n\n\nplease run ./a.out to see it work"



clean:
	rm a.out student_define.structjson.cpp student_define.structjson.h
